package com.atlas.dashboard.actions.domain;

import java.util.List;

import com.atlas.dashboard.actions.domain.AlertPlan.AlertRule;

/** Writes Atlas's observability-as-code manifest — the reviewable artifact format is ours. */
public final class AlertManifests {

    private AlertManifests() {
    }

    public static String yaml(String traceId, String component, List<AlertRule> rules) {
        StringBuilder y = new StringBuilder();
        y.append("# observability-as-code \u00b7 generated by Atlas from ").append(traceId).append("\n");
        y.append("apiVersion: atlas/v1\n");
        y.append("kind: AlertManifest\n");
        y.append("metadata:\n");
        y.append("  component: ").append(component).append("\n");
        y.append("  sourceTrace: ").append(traceId).append("\n");
        y.append("spec:\n");
        y.append("  alerts:\n");
        for (AlertRule r : rules) {
            y.append("    - name: ").append(r.name()).append("\n");
            y.append("      system: ").append(r.system()).append("\n");
            y.append("      query: >-\n");
            y.append("        ").append(r.query()).append("\n");
            y.append("      rationale: ").append(r.rationale()).append("\n");
        }
        return y.toString();
    }
}
